import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  authors: { name: "MahdiFayyaziMoghaddam" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-main-background text-main-text text-[62.5%] min-h-screen m-0 p-0 font-main selection:bg-main-primary scroll-smooth`}
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
