import type { Metadata } from "next";
import Sidebar from "@/components/organisms/Sidebar";
import Header from "@/components/organisms/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  authors: { name: "MahdiFayyaziMoghaddam" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-[62.5%] box-border">
      <body
        className={`antialiased flex justify-center items-stretch bg-main-background text-main-text min-h-screen text-[1.6rem] m-0 p-0 font-main selection:bg-main-primary scroll-smooth isolate`}
        cz-shortcut-listen="true"
      >
        <Sidebar />
        <main className="relative flex flex-col items-stretch grow overflow-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
